<?php
/**
 * Styles and scripts for the module 
 *
 * @package    BardCanvas
 * @subpackage emojione_for_bardcanvas
 * @author     Alejandro Caballero - lava.caballero@gmail.com
 *             
 * @var module $this_module
 * @var config $config
 */

use hng2_base\config;
use hng2_base\module;
?>

<!-- emoji one for bardcanvas -->

<link rel="stylesheet" type="text/css"
      href="<?= $config->full_root_path ?>/<?= $this_module->name ?>/media/global_styles~v<?=$config->scripts_version?>.css">
